
# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Color constants (TODO: make this to sprites down the line)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BACKGROUND_COLOR = (30, 30, 30)

# Player settings
PLAYER_COLOR = (255, 0, 0)
PLAYER_WIDTH = 16
PLAYER_HEIGHT = 32
PLAYER_MAX_SPEED = 15
PLAYER_ACCELERATION = 0.8
PLAYER_FRICTION = 0.7
PLAYER_GRAVITY = 0.5
PLAYER_JUMP_FORCE = 10
PLAYER_FLIP_MAX_VELOCITY = 2 
PLAYER_JUMP_CUT_MULTIPLIER = 0.5  

# Tiles are square
TILE_SIZE_IN_SCREEN = 64

# Camera settings
CAMERA_MODE = False
DEBUG_MODE = True