# True for agent control, False for human
RL_CONTROL = {
    "player_one": True,
    "player_two": False,
}

TRAINING_MODE = False

ACTIONS = [
    "NOOP",
    "LEFT",
    "RIGHT", 
    "JUMP",
    "LEFT_JUMP",
    "RIGHT_JUMP"
]

ACTION_SPACE_SIZE = len(ACTIONS)

MINI_BATCH = 32
MEMORY_SIZE = 10000
NETWORK_SYNC_RATE = 20

DISCOUNT_GAMA = 0.99
LEARNING_RATE = 0.001

EPSILON_DECAY = 0.00001
MIN_EPSILON = 0.005

FRAME_SKIPPING_STEPS = 4

REWARD_FOR_WINNING = 10
REWARD_FOR_EXISTING = 0.5
REWARD_FOR_PROXIMITY = 0.2
PENALTY_FOR_RUNNING_OUT_THE_MAP = 0.5
PENALTY_FOR_STAGNATION = 0.1

START_REWARD = 50